// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateWritingSampleInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PerformanceInput struct {
	SampleID       string  `json:"sampleId"`
	TimeToComplete float64 `json:"timeToComplete"`
	Accuracy       float64 `json:"accuracy"`
	Wpm            float64 `json:"wpm"`
}

type WritingSample struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}
